on:
  pull_request:
    branches:
      - master

jobs:
  prebuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build 🏗️
        run: npm run build-storybook -- --quiet

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node